name: Create Tag

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript code
        run: npm run build

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global credential.helper '!f() { echo "username=GH_ACTION_TOKEN"; echo "password=${GH_ACTION_TOKEN}"; }; f'

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Create a new Git tag
        id: create_new_tag
        run: |
          latest_tag=${{ steps.get_latest_tag.outputs.latest_tag }}
          if [ "$latest_tag" == "v0.0.0" ]; then
            # If no tags exist, create the first tag
            new_tag="v1.0.0"
          else
            # If tags exist, increment the middle digit
            if [ "$(echo "$latest_tag" | cut -d'.' -f2)" -eq 999 ]; then
              # If middle digit is 999, increment the first digit
              new_tag=$(echo "$latest_tag" | awk -F. -v OFS=. '{$1 = $1 + 1; $2 = 0; $3 = 0;} 1')
            else
              # Otherwise, increment the middle digit
              new_tag=$(echo "$latest_tag" | awk -F. -v OFS=. '{$2 = $2 + 1; $3 = 0;} 1')
            fi
          fi

          # Check if the tag already exists
          if git rev-parse "$new_tag" >/dev/null 2>&1; then
            # If the tag exists, increment the last digit and create the new tag
            new_tag=$(echo "$new_tag" | awk -F. -v OFS=. '{$3 = $3 + 1;} 1')
            git tag -a "$new_tag" -m "Bump version to $new_tag [skip ci]"
            git push origin "$new_tag"
            echo "::set-output name=new_tag::$new_tag"
          else
            # If the tag doesn't exist, create it
            git tag -a "$new_tag" -m "Bump version to $new_tag [skip ci]"
            git push origin "$new_tag"
            echo "::set-output name=new_tag::$new_tag"
          fi

      - name: Use the new tag
        run: |
          echo "New tag: ${{ steps.create_new_tag.outputs.new_tag }}"
