name: Auto-increment version and publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Auto-increment version and publish
        run: |
          # Obtener el último tag o establecer el primer tag si no hay ninguno
          LAST_TAG=$(git describe --abbrev=0 --tags || echo "v1.0.0")

          # Dividir el tag en partes
          IFS='.' read -r -a VERSION_PARTS <<< "$LAST_TAG"

          # Incrementar el segundo número
          VERSION_PARTS[1]=$((VERSION_PARTS[1] + 1))

          # Verificar si el segundo número es 1000
          if [ "${VERSION_PARTS[1]}" -eq 1000 ]; then
            # Incrementar el primer número y resetear el segundo a 0
            VERSION_PARTS[0]=$((VERSION_PARTS[0] + 1))
            VERSION_PARTS[1]=0
          fi

          # Crear el nuevo tag
          NEW_TAG="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}"

          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"
